# Generated by Django 4.2.8 on 2024-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_available_book_borrowing_date_book_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
