# Generated by Django 4.2.8 on 2024-02-17 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_remove_book_borrowing_date_purchasehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseHistory',
            new_name='BorroBook',
        ),
    ]
