# Generated by Django 4.2.8 on 2024-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_purchasehistory_borrobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='balace_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
