# Generated by Django 4.2.8 on 2024-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_balace_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
